name: Build zakomksd

on:
  push:
    branches: [ "mian" ]
    paths:
      - '.github/workflows/zakomksd.yml'
      - 'userspace/zakomksd/**'
  workflow_dispatch:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      os:
        required: false
        type: string
        default: self-hosted

jobs:
  build-susfs:
    name: Build userspace zakomksd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build zakomksd
        working-directory: ./userspace/zakomksd
        run: |
          $ANDROID_NDK_HOME/ndk-build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zakomksd-aarch64-linux-android
          path: ./userspace/zakomksd/libs
